CREATE TABLE CONTROLLER
(
    ID          VARCHAR(36)  NOT NULL,
    PUBLISH_URI VARCHAR(100) NOT NULL,
    JAR_FILE_ID VARCHAR(36)  NOT NULL,
    CLASS_PATH  VARCHAR(100) NOT NULL,
    IS_ACTIVE   INTEGER      NOT NULL DEFAULT 1,
    CREATED_AT  TEXT         NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT  TEXT         NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_CONTROLLER PRIMARY KEY (PUBLISH_URI)
);

-- SQLite doesn't support ALTER COLUMN RENAME directly, need to use ALTER TABLE RENAME COLUMN
ALTER TABLE MOCK_RESPONSE RENAME COLUMN PUBLISH_URL TO PUBLISH_URI;
ALTER TABLE ENDPOINT RENAME COLUMN PUBLISH_URL TO PUBLISH_URI;
