version: '3.8'

services:
  app:
    image: dynamic-api
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:sqlite:/data/webservice.db
      SPRING_DATASOURCE_USERNAME: 
      SPRING_DATASOURCE_PASSWORD: 
    ports:
      - "8080:8080"
    volumes:
      - D:/tmp/sqlite:/data
